### PR TITLE
Don't change the deployment spec labels and selectors in mutate

### LINKED ISSUE #550: Deployment selector is immutable from the operator
If a user manages to change the deployment selector and the pod template labels for the memcached deployment the operator loops trying to reconcile with the following error:

`"msg":"Reconciler error","controller":"manageiq-controller","request":"manageiq/miq","error":"Deployment.apps \"memcached\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app\":\"manageiq\", \"name\":\"memcached\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable"`

This is because the kubernetes API made deployment selectors immutable in https://github.com/kubernetes/kubernetes/pull/50719

The problem is with `oc` version 3.11 and a 3.11 cluster you can issue a patch to the deployment which will successfully edit the deployment selectors:

```
I0617 15:34:57.766278   36199 request.go:897] Request Body: {"spec":{"selector":{"matchLabels":{"things":"stuff"}},"template":{"metadata":{"labels":{"things":"stuff"}}}}}
I0617 15:34:57.766326   36199 round_trippers.go:386] curl -k -v -XPATCH  -H "Content-Type: application/strategic-merge-patch+json" -H "Authorization: Bearer tokenhereasdf" -H "User-Agent: oc/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0" -H "Accept: application/json" 'https://cluster.example.com:8443/apis/extensions/v1beta1/namespaces/manageiq/deployments/memcached'
I0617 15:34:57.809250   36199 round_trippers.go:405] PATCH https://cluster.example.com:8443/apis/extensions/v1beta1/namespaces/manageiq/deployments/memcached 200 OK in 42 milliseconds
I0617 15:34:57.809271   36199 round_trippers.go:411] Response Headers:
I0617 15:34:57.809277   36199 round_trippers.go:414]     Date: Wed, 17 Jun 2020 19:34:57 GMT
I0617 15:34:57.809295   36199 round_trippers.go:414]     Cache-Control: no-store
I0617 15:34:57.809310   36199 round_trippers.go:414]     Content-Type: application/json
I0617 15:34:57.809319   36199 round_trippers.go:414]     Content-Length: 2345
I0617 15:34:57.809371   36199 request.go:897] Response Body: {"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"memcached","namespace":"manageiq","selfLink":"/apis/extensions/v1beta1/namespaces/manageiq/deployments/memcached","uid":"36a525b4-b0ce-11ea-9870-d094660d31fb","resourceVersion":"9925629","generation":4,"creationTimestamp":"2020-06-17T19:10:31Z","labels":{"app":"manageiq"},"annotations":{"deployment.kubernetes.io/revision":"2"},"ownerReferences":[{"apiVersion":"manageiq.org/v1alpha1","kind":"ManageIQ","name":"miq","uid":"35bb4598-b0ce-11ea-9870-d094660d31fb","controller":true,"blockOwnerDeletion":true}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"manageiq","name":"memcached","things":"stuff"}},"template":{"metadata":{"name":"memcached","creationTimestamp":null,"labels":{"app":"manageiq","name":"memcached","things":"stuff"}},"spec":{"containers":[{"name":"memcached","image":"manageiq/memcached:latest","ports":[{"containerPort":11211,"protocol":"TCP"}],"env":[{"name":"MEMCACHED_MAX_MEMORY","value":"64"},{"name":"MEMCACHED_MAX_CONNECTIONS","value":"1024"},{"name":"MEMCACHED_SLAB_PAGE_SIZE","value":"1m"}],"resources":{},"livenessProbe":{"tcpSocket":{"port":11211},"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"tcpSocket":{"port":11211},"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":10,"progressDeadlineSeconds":600},"status":{"observedGeneration":3,"replicas":1,"updatedReplicas":1,"readyReplicas":1,"availableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2020-06-17T19:11:43Z","lastTransitionTime":"2020-06-17T19:11:43Z","reason":"MinimumReplicasAvailable","message":"Deployment has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2020-06-17T19:24:52Z","lastTransitionTime":"2020-06-17T19:10:31Z","reason":"NewReplicaSetAvailable","message":"ReplicaSet \"memcached-ddc6b6f75\" has successfully progressed."}]}}
```

I believe this is because the request is going to the `extensions/v1beta1` endpoint rather than whatever the one used by the operator-sdk is.

1. Deploy the app using the operator
2. `oc edit deploy memcached` and edit the deployment spec selector and pod template spec labels to some new, but still matching, value
3. Observe failures in operator logs

- ManageIQ version: master
- Minikube/KIND/OCP/CRC version: 3.11
- Kubernetes version: (use `kubectl version`):
```
$ oc version
oc v3.11.43
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cluster.example.com:8443
openshift v3.11.216
kubernetes v1.11.0+d4cacc0
```

I think we can address this by providing the deployment spec selector and pod template spec labels in the deployment struct we pass to CreateOrUpdate and specifically not editing those fields in the mutate function.

### PR DESCRIPTION
**Pull request by bdunne**
Fixes #550

### CODE REVIEW

File: manageiq-operator/pkg/helpers/miq-components/memcached.go [hunk 1]
```diff
@@ -62,38 +62,33 @@ func NewMemcachedDeployment(cr *miqv1alpha1.ManageIQ, scheme *runtime.Scheme) (*
...
 	}
 
 	f := func() error {
 		if err := controllerutil.SetControllerReference(cr, deployment, scheme); err != nil {
 			return err
 		}
-		if deployment.ObjectMeta.Labels == nil {
-			deployment.ObjectMeta.Labels = make(map[string]string)
-		}
-		deployment.ObjectMeta.Labels["app"] = cr.Spec.AppName
```
Comment (carbonin) [inline manageiq-operator/pkg/helpers/miq-components/memcached.go:95]: I think we should keep this in.

File: manageiq-operator/pkg/helpers/miq-components/memcached.go [hunk 2]
```diff
@@ -62,38 +62,33 @@ func NewMemcachedDeployment(cr *miqv1alpha1.ManageIQ, scheme *runtime.Scheme) (*
...
-	}
-
 	deployment := &appsv1.Deployment{
 		ObjectMeta: metav1.ObjectMeta{
 			Name:      "memcached",
 			Namespace: cr.ObjectMeta.Namespace,
+			Labels:    podLabels,
+		},
+		Spec: appsv1.DeploymentSpec{
+			Replicas: &repNum,
```
Comment (carbonin) [inline manageiq-operator/pkg/helpers/miq-components/memcached.go:72]: Putting this here prevents us from reconciling the replicas. I was thinking maybe we set the replicas, and template in the reconcile function rather than the entire deployment spec.

File: manageiq-operator/pkg/helpers/miq-components/memcached.go [hunk 3]
```diff
@@ -62,38 +62,33 @@ func NewMemcachedDeployment(cr *miqv1alpha1.ManageIQ, scheme *runtime.Scheme) (*
...
-				Containers: []corev1.Container{container},
-			},
-		},
-	}
-
 	deployment := &appsv1.Deployment{
 		ObjectMeta: metav1.ObjectMeta{
 			Name:      "memcached",
 			Namespace: cr.ObjectMeta.Namespace,
+			Labels:    podLabels,
```
Comment (carbonin) [inline manageiq-operator/pkg/helpers/miq-components/memcached.go:69]: This is technically a change in behavior. Previously this label set only contained the "app" key where now it would have "name" and "app"

**Comment by carbonin** [comment]
Also removed `jansa/yes?` as we didn't originally backport the mutate function changes

**Comment by carbonin** [comment]
Also I think it might be a good idea to change this for PG too as the patch would be similar and I believe it's [subject to the same problem](https://github.com/ManageIQ/manageiq-pods/pull/547#discussion_r441809801)

File: manageiq-operator/pkg/helpers/miq-components/postgresql.go [hunk 4]
```diff
@@ -191,44 +191,23 @@ func NewPostgresqlDeployment(cr *miqv1alpha1.ManageIQ, scheme *runtime.Scheme) (
 
 	var repNum int32 = 1
```
Comment (carbonin) [inline manageiq-operator/pkg/helpers/miq-components/postgresql.go:192]: Can you just move this into the mutate function since it's a constant?

File: manageiq-operator/pkg/helpers/miq-components/memcached.go [hunk 5]
```diff
@@ -62,27 +62,24 @@ func NewMemcachedDeployment(cr *miqv1alpha1.ManageIQ, scheme *runtime.Scheme) (*
 	}
 	var repNum int32 = 1
```
Comment (carbonin) [inline manageiq-operator/pkg/helpers/miq-components/memcached.go:63]: Same here, the only place this is used is the mutate function.
